[package]
name = "bdd"
version = "0.1.0"
authors = ["Matt Salter <bdd@hemiptera.org>"]
description = "A binary data definition and processing language"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
lalrpop-util = "0.19.7"
regex = "1.5.5"